on:
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Run tests
        run: crystal spec
      - name: Build for linux
        if: ${{ matrix.os != 'macos-latest' }}
        run: shards build -obin/${{ matrix.os }}
      - name: Build for macos
        if: ${{ matrix.os == 'macos-latest' }}
        run: shards build -obin/${{ matrix.os }}
